# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfg',
            name='port',
            field=models.IntegerField(default=4433),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cfg',
            name='protocol',
            field=models.CharField(choices=[('BGP', 'BGP'), ('SSL', 'SSL')], default='BGP', max_length=3),
        ),
    ]
