# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20160604_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfg',
            name='myas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='nlriPrefix',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='nlriRepeat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='nriLen',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='pathFlag',
            field=models.IntegerField(default=62),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='pathLen',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='pathType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='pathValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='pathValueNextHop',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='repeatUpdate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='routerID',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='version',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='withdrawnPrefix',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfg',
            name='withdrawnRoute',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cfg',
            name='protocol',
            field=models.CharField(choices=[('BGP', 'BGP'), ('SSL', 'SSL'), ('SSL_PERF', 'SSL_PERF')], default='BGP', max_length=8),
        ),
    ]
