# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20160618_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfg',
            old_name='ovTCP',
            new_name='ovProtocol',
        ),
        migrations.RemoveField(
            model_name='cfg',
            name='ovUDP',
        ),
    ]
